services:
  db:
    image: timescale/timescaledb-ha:pg18
    container_name: local_timescaledb
    restart: always
    environment:
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: devdb
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data